### ISSUE TITLE
[New] automation blueprint for Paulmann 501.34

### ISSUE THREAD

**Issue by Flo-R1der** [Flo-R1der/My_Smart-Home_stuff#3]
[Zigbee2MQTT Device Info page](https://www.zigbee2mqtt.io/devices/501.34.html#paulmann-501.34)

current automation:

``````
alias: Mehrfachtaster Eingangstür
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.mehrfachtaster_eingangstur_action
    to:
      - on_1
      - brightness_move_up_1
      - off_1
      - brightness_move_down_1
      - on_2
      - brightness_move_up_2
      - off_2
      - brightness_move_down_2
    enabled: true
variables:
  received_state: "{{ trigger.to_state.state }}"
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ received_state == 'on_1' }}"
        sequence: []
        alias: Top Left (short)
      - conditions:
          - condition: template
            value_template: "{{ received_state == 'brightness_move_up_1' }}"
        sequence: []
        alias: Top Left (long)
      - conditions:
          - condition: template
            value_template: "{{ received_state == 'off_1' }}"
        sequence:
          - action: light.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: light.alle_lichter_wohnung
        alias: Bottom Left (short)
      - conditions:
          - condition: template
            value_template: "{{ received_state == 'brightness_move_down_1' }}"
        sequence: []
        alias: Bottom Left (long)
      - conditions:
          - condition: template
            value_template: "{{ received_state == 'on_2' }}"
        sequence:
          - action: automation.trigger
            metadata: {}
            data:
              skip_condition: true
            target:
              entity_id: automation.staubsauger_roboter
        alias: Top Right (short)
      - conditions:
          - condition: template
            value_template: "{{ received_state == 'brightness_move_up_2' }}"
        sequence: []
        alias: Top Right (long)
      - conditions:
          - condition: template
            value_template: "{{ received_state == 'off_2' }}"
        sequence:
          - action: script.sonnenschutz_position_rollladen
            metadata: {}
            data: {}
        alias: Bottom Right (short)
      - conditions:
          - condition: template
            value_template: "{{ received_state == 'brightness_move_down_2' }}"
        sequence:
          - action: cover.close_cover
            metadata: {}
            data: {}
            target:
              entity_id: cover.alle_rolladen_wohnung
        alias: Bottom Right (long)
mode: single
``````
